modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/2Retr0/QuickStack/issues"

[[mods]]
modId="quickstack"
version="${version}"
displayName="QuickStack"
authors="2Retr0"
displayURL="https://github.com/2Retr0/QuickStack"
logoFile="assets/quickstack/icon.png"
description='''
Adds the ability to quick stack to nearby chests!
'''

[[mixins]]
config="quickstack.mixins.json"
config="quickstack.client.mixins.json"
config="quickstack.client.mixins.sodium.json"

[[dependencies.quickstack]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.quickstack]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.quickstack]]
modId="cloth_config"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.quickstack]]
modId="architectury"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"
